version: "3.8"
services:
  db:
    image: postgres:17
    container_name: fastapi_postgres_db
    environment:
      POSTGRES_USER: trendmagazine
      POSTGRES_PASSWORD: 0822
      POSTGRES_DB: trendmagazine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
